GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO school_user;

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO school_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON TABLES TO school_user;GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO school_user;

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO school_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON TABLES TO school_user;